# Generated by Django 4.1.5 on 2023-01-29 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Report_ID', models.IntegerField(unique=True, verbose_name='Report ID')),
                ('Behavior', models.CharField(max_length=120, verbose_name='Behavior')),
                ('Signature', models.CharField(max_length=120, verbose_name='Signature')),
                ('Metadata', models.CharField(max_length=120, verbose_name='Metadata')),
                ('Others', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Privacy_Type', models.CharField(max_length=8, verbose_name='Privacy_Type')),
                ('Create_Date', models.DateTimeField(verbose_name='Creation_Date')),
                ('Sample_Type', models.CharField(max_length=5, verbose_name='Sample_Type')),
                ('Sample_Address', models.TextField(null=True, verbose_name='Sample_Address')),
                ('ReportID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.report')),
                ('UserID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
