# Generated by Django 4.1.5 on 2023-01-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FahisUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_ID', models.IntegerField(verbose_name='User ID')),
                ('fname', models.CharField(max_length=120, verbose_name='First Name')),
                ('lname', models.CharField(max_length=120, verbose_name='Last name')),
                ('User_Email', models.EmailField(max_length=254, verbose_name='User Email')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Report_ID', models.IntegerField(unique=True, verbose_name='Report ID')),
                ('Behavior', models.CharField(max_length=120, verbose_name='Behavior')),
                ('Signature', models.CharField(max_length=120, verbose_name='Signature')),
                ('Metadata', models.CharField(max_length=120, verbose_name='Metadata')),
                ('Others', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReportID', models.IntegerField(null=True, verbose_name='UserID')),
                ('Privacy_Type', models.CharField(max_length=8, verbose_name='Privacy Type')),
                ('Create_Date', models.DateTimeField(verbose_name='Creation Date')),
                ('Sample_Type', models.CharField(max_length=5, verbose_name='Sample Type')),
                ('UserID', models.IntegerField(null=True, verbose_name='UserID')),
                ('Sample_Address', models.TextField(null=True, verbose_name='Sample Address')),
            ],
        ),
    ]
