# Generated by Django 4.1.5 on 2023-02-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='Behavior',
        ),
        migrations.RemoveField(
            model_name='report',
            name='Metadata',
        ),
        migrations.RemoveField(
            model_name='report',
            name='Others',
        ),
        migrations.RemoveField(
            model_name='report',
            name='Signature',
        ),
        migrations.AddField(
            model_name='report',
            name='Duration',
            field=models.IntegerField(default=60, verbose_name='Duration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='Network',
            field=models.JSONField(null=True, verbose_name='Network'),
        ),
        migrations.AddField(
            model_name='report',
            name='Processes',
            field=models.JSONField(null=True, verbose_name='Processes'),
        ),
        migrations.AddField(
            model_name='report',
            name='Score',
            field=models.IntegerField(default=5, verbose_name='Score'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sample',
            name='Create_Date',
            field=models.DateTimeField(verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='Privacy_Type',
            field=models.CharField(max_length=8, verbose_name='Privacy Type'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='Sample_Address',
            field=models.TextField(null=True, verbose_name='Sample Address'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='Sample_Type',
            field=models.CharField(max_length=5, verbose_name='Sample Type'),
        ),
    ]
