# Generated by Django 4.1.5 on 2023-02-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_report_report_address_report_report_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='Duration',
            field=models.IntegerField(null=True, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='report',
            name='Score',
            field=models.IntegerField(null=True, verbose_name='Score'),
        ),
    ]
