# Generated by Django 4.1.5 on 2023-02-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_report_duration_alter_report_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id'),
        ),
    ]
