# Generated by Django 4.1.5 on 2023-02-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_sample_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='id'),
        ),
    ]
