# Generated by Django 4.1.5 on 2023-02-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_sample_sample_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='Report_ID',
            field=models.IntegerField(auto_created=True, unique=True, verbose_name='Report ID'),
        ),
    ]
