# Generated by Django 4.1.5 on 2023-02-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_report_report_address_alter_report_report_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='Report_ID',
            field=models.IntegerField(auto_created=True, null=True, unique=True, verbose_name='Report_ID'),
        ),
    ]
