# Generated by Django 4.1.5 on 2023-02-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_remove_report_id_alter_report_report_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='task_id',
            field=models.IntegerField(null=True, verbose_name='task_id'),
        ),
        migrations.AddField(
            model_name='sample',
            name='Environment',
            field=models.TextField(null=True, verbose_name='Environment'),
        ),
    ]
